apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: bgdemo-service
    app.kubernetes.io/part-of: app-bgdemo-service
  name: bgdemo-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bgdemo-service
      app.kubernetes.io/part-of: app-bgdemo-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: bgdemo-service
        app.kubernetes.io/part-of: app-bgdemo-service
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cicd/bgdemo-service:dev
        imagePullPolicy: Always
        name: bgdemo-service
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
