apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/masauve/bgdemo
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: bgdemo
    app.kubernetes.io/component: bgdemo
    app.kubernetes.io/instance: bgdemo
    app.kubernetes.io/name: bgdemo
    app.kubernetes.io/part-of: bgdemo-app
    app.openshift.io/runtime: php
    app.openshift.io/runtime-version: 7.4-ubi8
  name: bgdemo
  namespace: secdemo
spec:
  lookupPolicy:
    local: false
