apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-pull
  namespace: dev
subjects:
- kind: ServiceAccount
  name: default 
  apiGroup: ""
roleRef:
  kind: Role
  name: system:image-puller 
  namespace: cicd
  apiGroup: ""
